#!/bin/bash
# Fix Looker Sync - Quick Reference Guide

echo "═══════════════════════════════════════════════════════════"
echo "  Looker Sync Fix Guide"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 ISSUE: Looker data hasn't synced since Jan 20, 2:01 PM"
echo "❌ CAUSE: Missing GMAIL_APP_PASSWORD in .env"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 1: Get Gmail App Password"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Visit: https://myaccount.google.com/apppasswords"
echo "2. Sign in with: vrocha@suitsupply.com"
echo "3. Generate new password for 'Mail' → 'Stockroom Dashboard'"
echo "4. Copy the 16-character password (remove spaces)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 2: Add Password to .env"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run this command (replace xxxx... with your password):"
echo ""
echo "  nano /var/www/stockroom-dashboard/.env"
echo ""
echo "Add this line:"
echo ""
echo "  GMAIL_APP_PASSWORD=xxxxxxxxxxxxxxxx"
echo ""
echo "Save and exit (Ctrl+O, Enter, Ctrl+X)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 3: Restart Dashboard"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  pm2 restart stockroom-dashboard"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 4: Test Manual Sync"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run this to test immediately:"
echo ""
echo "  cd /var/www/stockroom-dashboard"
echo "  node utils/unified-gmail-processor.js run"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Automatic Processing"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ Gmail Watch: Active (expires Jan 29)"
echo "✅ Webhook: Configured at /api/webhooks/gmail"
echo "✅ Cron: Runs every 30 minutes"
echo ""
echo "Once password is added, Looker data will sync automatically:"
echo "  • When Gmail receives new Looker emails (push notification)"
echo "  • Every 30 minutes (scheduled check)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Monitor Sync Activity"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check today's log:"
echo "  tail -f /var/lib/stockroom-dashboard/data/scheduler-logs/unified-gmail-$(date +%Y-%m-%d).log"
echo ""
echo "Check sync results:"
echo "  cat /var/lib/stockroom-dashboard/data/sync-results/$(date +%Y-%m-%d).json | jq"
echo ""
echo "═══════════════════════════════════════════════════════════"
